# DataGraft API

<div style="background:#0DBC37;min-height:260px;color:white;margin-bottom:1em;border-radius:6px;">

<h2 style="color:white;padding-top: 2.7em;text-align: left;margin-left: 0.6em;margin-right: 1em;font-size:3em;max-width:500px">Making data work for your apps</h2>

</div>

<!-- include(security-and-authentication.apib) -->

<!-- include(model-reference.apib) -->

# Group Usage

### Endpoint

```
https://api.datagraft.net/
```

### Parameters

Unless otherwise stated, all the parameters are **header parameters**. It means they are sent in the HTTP headers.

For example, the `q` search parameter of a catalog search is sent in the HTTP headers:
```
GET /catalog/datasets/search HTTP/1.1
Host: api.datagraft.net
Accept: application/ld+json
Accept-Encoding: gzip, deflate, sdch
Authorization: Basic a2V5OnNlY3JldA==
q: mysearch 
```


<!-- include(datasets-catalog.apib) -->

<!-- include(rdf-repositories.apib) -->

<!-- include(transformations-catalog.apib) -->

<!-- include(grafter-transformations.apib) -->
