# Datagraft API

<div style="background:url(http://medias.master-bridge.eu/resize/640/480/47755241ca8e7eb4dfe5e796c631a2da6ee154e9.jpeg) no-repeat;background-size:cover;min-height:300px;color:white;margin-bottom:1em;">

<h2 style="color:white;text-align:center;padding-top:3em;">Making open data work for your apps</h2>

</div>

<!-- include(security-and-authentication.apib) -->

<!-- include(model-reference.apib) -->

# Group Usage

### Endpoint

```
https://api.datagraft.net/
```

### Parameters

Unless otherwise stated, all the parameters are **header parameters**. It means they are sent in the HTTP headers.

For example, the `q` search parameter of a catalog search is sent in the HTTP headers:
```
GET /catalog/datasets/search HTTP/1.1
Host: api.datagraft.net
Accept: application/ld+json
Accept-Encoding: gzip, deflate, sdch
Authorization: Basic a2V5OnNlY3JldA==
q: mysearch 
```

<!-- include(datasets-catalog.apib) -->

<!-- include(rdf-repositories.apib) -->
