# Datagraft API

<div style="background:url(http://medias.master-bridge.eu/resize/640/480/47755241ca8e7eb4dfe5e796c631a2da6ee154e9.jpeg) no-repeat;background-size:cover;min-height:300px;color:white;margin-bottom:1em;">

<h2 style="color:white;text-align:center;padding-top:3em;">Making open data work for your apps</h2>

</div>

<!-- include(security-and-authentication.md) -->

<!-- include(model-reference.md) -->

<!-- include(datasets-catalog.md) -->
