# Group Security and authentication

The Datagraft API is restricted to authenticated application, using an access key and a secret. You can manage your access keys and secrets using the [Datagraft API key manager](http://datagraft.net/pages/keymanager/index.jsp).


#### HTTPS

The API is only accessible through HTTPS.


#### Authentication

The authentication is done using HTTP Basic authentication, and therefore the HTTP authorization header field. It consists of the text 'Basic ' concatenated with the base64 encoding of the API key and the API secret separated by a colon.

Example in JavaScript:
```javascript
>> request.headers.Authorization = 'Basic ' + btoa(key + ':' + secret);
=> "Basic a2V5OnNlY3JldA=="
```

#### CORS

The Datagraft API supports [cross-origin requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) without domains restrictions.